import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/components/providers/SessionProvider";
import { UserContextProvider } from "@/context/user.context";

export const metadata: Metadata = {
  title: "Full Stack Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <UserContextProvider>
            {children}
          </UserContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
